<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOADevelopment/GestaoBiblioteca/ConsultarLivrosDB" name="ConsultarLivrosDB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ConsultarLivrosDB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOADevelopment/GestaoBiblioteca/ConsultarLivrosDB"/>
    <wsdl:binding name="ConsultarLivrosDB_ptt-binding" type="con:ConsultarLivrosDB_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/SOADevelopment/GestaoBiblioteca/ConsultarLivrosDB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultarLivrosDB">
            <soap:operation soapAction="ConsultarLivrosDB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>